cats99_2/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]

  resources :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

cats99_2/app/controllers/session_controller.rb
class SessionController < ApplicationController
    before_action :redirect_if_logged_in, only: [:new, :create]

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(
            params[:session][:user][:user_name],
            params[:session][:user][:password]
            )
        if @user
            login!(@user)
            redirect_to cats_url
        else
            redirect_to new_session_url
        end
    end


    def destroy
        if current_user 
                current_user.reset_session_token!
        end
        session[:session_token] = nil
    end
end

cats99_2/app/views/session/new.html.erb
<h1>Log In</h1>

<form action="<%= session_index_url %>" method="POST">

    <label for="username">Username:
        <input id="username" type="text" name="session[user][user_name]" value="<%= @user.user_name %>">
    </label>
    
    <label for="password">Password:
        <input id="password" type="password" name="session[user][password]" value="">
    </label>
    
    <input type="submit" value="Login">

</form>